# Generated by Django 4.2.1 on 2023-06-18 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_name_customer_first_name_customer_last_name'),
        ('interactions', '0003_alter_interaction_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatlog', to='interactions.interaction'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emaillog', to='interactions.interaction'),
        ),
        migrations.AlterField(
            model_name='image',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='interactions.interaction'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interactions', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interactions.chatlog'),
        ),
    ]
