# Generated by Django 4.2.1 on 2023-06-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_alter_emaillog_options_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
