# Generated by Django 4.2.1 on 2023-06-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_alter_chatlog_interaction_alter_emaillog_interaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatlog',
            options={'ordering': ['started_at']},
        ),
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
