# Generated by Django 4.2.1 on 2023-07-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0007_alter_emaillog_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='participants',
        ),
    ]
