# Generated by Django 4.2.1 on 2023-07-05 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_remove_emaillog_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), null=True, size=None),
        ),
    ]
