# Generated by Django 4.2.1 on 2023-07-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0009_emaillog_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['sent_at']},
        ),
    ]
