version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    
  api:
    image: turianpy/kekcrm_api:latest
    restart: always
    volumes:
      - static_backend:/app/static_backend/
      - media_backend:/app/media_backend/
      - crm_api:app
    depends_on:
      - db
    env_file:
      - ./.env
    
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_backend:/var/html/static_backend/
      - media_backend:/var/html/media_backend/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  static_backend:
  media_backend:
  db: