version: '3.8'
services:

  crm_db:
    image: postgres:13.0-alpine
    volumes:
      - crm_db:/var/lib/postgresql/data
    env_file:
      - ./.env
    
  crm_api:
    image: turianpy/crm_api:latest
    restart: always
    volumes:
      - static_backend:/app/static_backend/
      - media_backend:/app/media_backend/
      - ../crm_api:/app
    depends_on:
      - crm_db
    env_file:
      - ./.env
    
  crm_nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_backend:/var/html/static_backend/
      - media_backend:/var/html/media_backend/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - crm_api

volumes:
  static_backend:
  media_backend:
  crm_db: