# Generated by Django 4.2.1 on 2023-06-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_business_options_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
