# Generated by Django 4.2.1 on 2023-06-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_staff_remove_user_role_delete_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
