name: kekcrm workflow

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - 'README.md'

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
    - name: run migrations
      run: |
        export SECRET_KEY=${{ secrets.SECRET_KEY }}
        python manage.py makemigrations
        python manage.py migrate
    - name: run tests
      run: |
        export SECRET_KEY=${{ secrets.SECRET_KEY }}
        python -m flake8 --exclude migrations,settings.py --ignore I001, I004
        pytest
    - name: notify if failed
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} - Job ${{ job.name }} failed with err code ${{ job.conclusion }}
  push_new_img_to_dhub:
    name: Push new image to docker hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kekcrm:latest
          file: Dockerfile
      - name: notify if failed
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} - Job ${{ job.name }} failed with err code ${{ job.conclusion }}
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send msg
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} - completed successfully